platform :ios, '10.0'
use_frameworks!
swift_version = "5.0"

target 'RxPermission_Example' do
  pod 'RxPermission/Location', :path => '../'
  pod "Permission", :git => "https://github.com/systembugtj/Permission.git"
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
              config.build_settings['ENABLE_TESTABILITY'] = 'YES'
              config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end

